name: licensed
on: [pull_request]

jobs:
  licensed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jonabc/setup-licensed@v1
        with:
          version: 2.x
      - run: npm ci
      - run: licensed cache
      - run: licensed status
